#!bin/env ruby
# this makes the editor use ruby syntax highlighting etc

### ec2 instances related rules ###
stackless_ec2_delete_rule do |instance|
  age = Time.now - instance.launch_time

  (age > 5.mins) && instance.name.match(/test/i)
  false
end
