#!bin/env ruby
# this makes the editor use ruby syntax highlighting etc

### ec2 instances related rules ###
stackless_ec2_delete_rule do |instance|
  # age = Time.now - instance.launch_time

  # (age > 3.days) && instance.name.empty?
  true
end
